### ISSUE TITLE
System.ArgumentNullException during debugging via Visual Studio

### ISSUE THREAD

**Issue by gabesmsft** [Azure/azure-functions-dotnet-worker-preview#20]
I understand that the Visual Studio debugging experience is still being worked on, but I want to report this issue in case it isn't a known issue.
**The following issue happens even when I uncomment the Debugger.Launch() statement. The same project works as expected when starting from command line or VS Code.**

Am using the sample code provided in this GitHub repo, as-is. Am hitting a System.ArgumentNullException during host startup issue that only happens in Visual Studio when running the following part of the sample code:
[https://github.com/Azure/azure-functions-dotnet-worker-preview/blob/main/FunctionApp/Program.cs#L22-L25](https://github.com/Azure/azure-functions-dotnet-worker-preview/blob/main/FunctionApp/Program.cs#L22-L25)

This issue can be consistently reproduced even on a fresh new Windows machine with the following software installed:
**Visual Studio 2019: version 16.8.3
Microsoft.NET SDK 5.0.100 x64
Azure Functions Core Tools 3.0.3160 (x64)**

Here is the full stack trace of the exception:
System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null. (Parameter 'value')
  Source=Google.Protobuf
  StackTrace:
   at Google.Protobuf.ProtoPreconditions.CheckNotNull[T](T value, String name)
   at Microsoft.Azure.WebJobs.Script.Grpc.Messages.StartStream.set_WorkerId(String value) in D:\a\1\s\src\DotNetWorker\obj\Release\net5.0\FunctionRpc.cs:line 1414
   at Microsoft.Azure.Functions.Worker.WorkerHostedService.<SendStartStreamMessageAsync>d__9.MoveNext() in D:\a\1\s\src\DotNetWorker\WorkerHostedService.cs:line 48
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.Functions.Worker.WorkerHostedService.<StartAsync>d__7.MoveNext() in D:\a\1\s\src\DotNetWorker\WorkerHostedService.cs:line 37
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at FunctionApp.Program.<Main>d__0.MoveNext() in C:\temp\FunctionsNet5\FunctionApp\Program.cs:line 32

**Comment by Spaceman1861** [comment]
I fixed this issue by changing this

`            var host = new HostBuilder()
                .ConfigureAppConfiguration(c => {})
                .ConfigureFunctionsWorker((c, b) =>
                {
                    b.UseFunctionExecutionMiddleware();
                })
                .Build();`

To this

`            var host = new HostBuilder()
                .ConfigureAppConfiguration(c => {
                    c.AddCommandLine(args);
                })
                .ConfigureFunctionsWorker((c, b) =>
                {
                    b.UseFunctionExecutionMiddleware();
                })
                .Build();`

Didnt really dig into why, hope it helps

**Comment by gabesmsft** [comment]
I am already using the ConfigureAppConfiguration(c =>{c.AddCommandLine(args);}) lines (it was already part of this github repo when I downloaded the code), but am hitting the described issue in Visual Studio all the same, but thanks for your reply.

**Comment by synercoder** [comment]
I have this same issue, first I created a new project and followed the readme. Then I started hitting this issue. So I thought perhaps I did something wrong, cloned the project, tried to launch that as well and....

![Screenshot showing bug](https://user-images.githubusercontent.com/18616295/103560994-041f2b80-4eb9-11eb-9a58-e12278688fe0.png)

The "fix" mentioned by @Spaceman1861 did not work for me, no matter what combo of configure I did or didn't use.

**Comment by synercoder** [comment]
Solved:

You can not debug the application directly using Visual Studio.

You can only start by using the command line `func host start`. If you do not, Visual Studio will try to debug the application directly instead of serving it using an out-of-process host that starts it.

I think this issue can be closed as @gabesmsft and me not understanding / reading the readme good enough.
