### ISSUE TITLE
Value cannot be null.

### ISSUE THREAD

**Issue by Matthewsre** [Azure/azure-functions-dotnet-worker-preview#33]
I am able to get the sample project working no problem, but when implementing in my project I am getting the following:

```
[2021-01-18T20:49:47.490Z] Starting JobHost
[2021-01-18T20:49:47.493Z] Starting Host (HostId=desktopa3osssd-381178134, InstanceId=cc9eb68f-d67c-44aa-ada1-ccd11f1235bf, Version=3.0.15193.0, ProcessId=47656, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=(null))
[2021-01-18T20:49:47.507Z] Loading functions metadata
[2021-01-18T20:49:47.509Z] FUNCTIONS_WORKER_RUNTIME set to dotnet-isolated. Skipping WorkerConfig for language:java
[2021-01-18T20:49:47.510Z] FUNCTIONS_WORKER_RUNTIME set to dotnet-isolated. Skipping WorkerConfig for language:node
[2021-01-18T20:49:47.511Z] FUNCTIONS_WORKER_RUNTIME set to dotnet-isolated. Skipping WorkerConfig for language:powershell
[2021-01-18T20:49:47.512Z] FUNCTIONS_WORKER_RUNTIME set to dotnet-isolated. Skipping WorkerConfig for language:python
[2021-01-18T20:49:47.512Z] Reading functions metadata
[2021-01-18T20:49:47.515Z] 0 functions found
[2021-01-18T20:49:47.534Z] 0 functions loaded
[2021-01-18T20:49:47.661Z] A host error has occurred during startup operation 'dd3f5c65-849a-4b81-90b0-9522000dca4f'.
[2021-01-18T20:49:47.662Z] Microsoft.Azure.WebJobs.Script: WorkerCofig for runtime: dotnet-isolated not found.
[2021-01-18T20:49:47.667Z] Stopping JobHost
Value cannot be null. (Parameter 'provider')
[2021-01-18T20:49:47.683Z] Initialization cancellation requested by runtime.
[2021-01-18T20:49:47.689Z] Stopping host...
[2021-01-18T20:49:47.690Z] Host shutdown completed.
```

Not sure if this is a problem with the serviceProvider not automatically being registered or related to the "dotnet-isolated not found" .

Any info to help me find the full stack trace to provide more details on this bug (or fix if issue is on my end)?

EDIT: Looks like I missed this package reference:
<PackageReference Include="Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator" Version="1.2.0" />

Now I am getting the following issue, which would be a duplicate of https://github.com/Azure/azure-functions-dotnet-worker-preview/issues/21

```
[2021-01-18T21:42:52.582Z] Loading functions metadata
[2021-01-18T21:42:52.616Z] FUNCTIONS_WORKER_RUNTIME set to dotnet-isolated. Skipping WorkerConfig for language:java
[2021-01-18T21:42:52.625Z] FUNCTIONS_WORKER_RUNTIME set to dotnet-isolated. Skipping WorkerConfig for language:node
[2021-01-18T21:42:52.637Z] FUNCTIONS_WORKER_RUNTIME set to dotnet-isolated. Skipping WorkerConfig for language:powershell
[2021-01-18T21:42:52.647Z] FUNCTIONS_WORKER_RUNTIME set to dotnet-isolated. Skipping WorkerConfig for language:python
[2021-01-18T21:42:52.650Z] Reading functions metadata
[2021-01-18T21:42:52.656Z] 0 functions found
[2021-01-18T21:42:52.667Z] 0 functions loaded
[2021-01-18T21:42:52.671Z] Loading extensions from C:\Dev\ServiceExtensions\src\Example.Function\bin\output\bin. BundleConfigured: False, PrecompiledFunctionApp: False, LegacyBundle: False
[2021-01-18T21:42:52.681Z] Loading startup extension '_Generated'
[2021-01-18T21:42:52.777Z] Loaded extension '_Generated' (1.0.0.0)
[2021-01-18T21:42:52.794Z] Loading startup extension 'AzureStorage'
[2021-01-18T21:42:52.800Z] Loaded extension 'AzureStorage' (4.0.3.0)
[2021-01-18T21:42:52.811Z] A host error has occurred during startup operation 'a40ee3e0-4f31-4289-8ac9-fa56a91e9554'.
[2021-01-18T21:42:52.812Z] Example.Function: Could not load file or assembly 'Microsoft.Extensions.Configuration.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
Value cannot be null. (Parameter 'provider')
[2021-01-18T21:42:52.827Z] Initialization cancellation requested by runtime.
[2021-01-18T21:42:52.832Z] Stopping host...
[2021-01-18T21:42:52.834Z] Host shutdown completed.
```

**Comment by AKomyshan** [comment]
Have your tried this tip: https://github.com/Azure/azure-functions-core-tools/issues/2232#issuecomment-695366552 ?

I have the same issue about few week ago, if tip doesn't help you provide please your Program.cs, {Function}.cs and .csproj files.

**Comment by Matthewsre** [comment]
> Have your tried this tip: [Azure/azure-functions-core-tools#2232 (comment)](https://github.com/Azure/azure-functions-core-tools/issues/2232#issuecomment-695366552) ?
> 
> I have the same issue about few week ago, if tip doesn't help you provide please your Program.cs, {Function}.cs and .csproj files.

Didn't have the mentioned folder there and the issue happens from both trying to debug in Visual Studio and from running `func host start --verbose`

Oddly when I try debugging from Visual Studio (I know it isn't currently supported), this is the stack trace I can extract from an error with the same message:

```
   at Google.Protobuf.ProtoPreconditions.CheckNotNull[T](T value, String name)
   at Microsoft.Azure.WebJobs.Script.Grpc.Messages.StartStream.set_WorkerId(String value) in D:\a\1\s\src\DotNetWorker\obj\Release\net5.0\FunctionRpc.cs:line 1414
   at Microsoft.Azure.Functions.Worker.WorkerHostedService.<SendStartStreamMessageAsync>d__9.MoveNext() in D:\a\1\s\src\DotNetWorker\WorkerHostedService.cs:line 48
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.Functions.Worker.WorkerHostedService.<StartAsync>d__7.MoveNext() in D:\a\1\s\src\DotNetWorker\WorkerHostedService.cs:line 37
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Example.Function.Program.<Main>d__0.MoveNext() in C:\Dev\ServiceExtensions\src\Example.Function\Program.cs:line 33
```

Here is my Program.cs:

```
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Azure.Functions.Worker.Configuration;
using Service.Extensions;
using Service.Extensions.Functions;
using Example.Repositories;

namespace Example.Function
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var host = new HostBuilder()
                .ConfigureAppConfiguration((hostBuilderContext, configurationBuilder) => {
                    configurationBuilder.AddCommandLine(args);
                    var env = hostBuilderContext.HostingEnvironment;
                    configurationBuilder.WithDefaultConfiguration(env.ContentRootPath, env.EnvironmentName, env.IsDevelopment(), "example");
                })
                .ConfigureFunctionsWorker((hostBuilderContext, functionsWorkerApplicationBuilder) => {
                    functionsWorkerApplicationBuilder.UseFunctionExecutionMiddleware();
                })
                .ConfigureServices((hostBuilderContext, serviceCollection) => {
                    serviceCollection.WithDefaultConfiguration(hostBuilderContext.Configuration);
                    serviceCollection.AddCosmos(hostBuilderContext.Configuration);
                    serviceCollection.AddTransient<CosmosRepository>();
                })
                .Build();

            await host.RunAsync();
        }
    }
}
```

Here is my .csproj file:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.0-preview1" OutputItemType="Analyzer"/>
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.0.0-preview1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Http" Version="3.0.2" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="4.0.3" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator" Version="1.2.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="3.1.11" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="System.Net.NameResolution" Version="4.3.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Example\Example.csproj" />
    <ProjectReference Include="..\Service.Extensions.Cosmos\Service.Extensions.Cosmos.csproj" />
    <ProjectReference Include="..\Service.Extensions.Functions\Service.Extensions.Functions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

Appreciate any help! :)

**Comment by tforkmann** [comment]
Got the same issue!

**Comment by xsoheilalizadeh** [comment]
Same here

**Comment by janpalas** [comment]
Also the same problem for me...

**Comment by aswell87** [comment]
Hopefully, this will help save someone sometime - I was suffering the same problem, and upgrading to the latest preview versions made it work.

`
<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.0-preview3" OutputItemType="Analyzer" /><PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.0.0-preview3" />`

**Comment by fabiocav** [comment]
This should be resolved with the latest drops. Closing as resolved, but please let us know if you continue to run into issues.
