### ISSUE TITLE
Service bus triggers dont work

### ISSUE THREAD

**Issue by onionhammer** [Azure/azure-functions-dotnet-worker-preview#46]
With 'Message' and 'string' I get the following

```
[2021-02-08T15:54:00.963Z] Executed 'Functions.Lead-DuplicateAppend' (Failed, Id=f631eddf-8094-4231-9b3e-2b88ae3c80b9, Duration=7ms)
[2021-02-08T15:54:00.992Z] System.Private.CoreLib: Exception while executing function: Functions.Lead-DuplicateAppend. System.Private.CoreLib: Result: Failure
Exception: Sequence contains no elements
Stack:    at System.Linq.ThrowHelper.ThrowNoElementsException()
[2021-02-08T15:54:00.993Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionExecutionContext context)
[2021-02-08T15:54:00.996Z]    at Microsoft.Azure.Functions.Worker.FunctionBroker.InvokeAsync(InvocationRequest invocationRequest) in D:\a\1\s\src\DotNetWorker\Broker\FunctionBroker.cs:line 44.
```

with byte[] I get:

```
[2021-02-08T15:50:53.608Z] System.Private.CoreLib: Exception while executing function: Functions.Lead-DuplicateAppend. System.Private.CoreLib: Result: Failure
Exception: Unable to convert to System.Byte[]
```

**Comment by sccrgoalie1** [comment]
I was having the same issue as you, but it turns out it was because I had an ILogger being injected.  I took that out and got the logger according to FunctionApp4 example.

This is working now.

```
public async Task Run([ServiceBusTrigger("system", Connection = "ServiceBusConnectionString")] Message myQueueItem, FunctionExecutionContext executionContex )
        {
            var log = executionContext.Logger;

}
```

**Comment by fabiocav** [comment]
Closing this in favor of https://github.com/Azure/azure-functions-dotnet-worker/issues/106

Please follow that issue for updates on how to use Service Bus.

**Comment by onionhammer** [comment]
> I was having the same issue as you, but it turns out it was because I had an ILogger being injected. I took that out and got the logger according to FunctionApp4 example.
> 
> This is working now.
> 
> ```
> public async Task Run([ServiceBusTrigger("system", Connection = "ServiceBusConnectionString")] Message myQueueItem, FunctionExecutionContext executionContex )
>         {
>             var log = executionContext.Logger;
> 
> }
> ```

Weird.. the injection is broken then?

**Comment by anthonychu** [comment]
`ILogger` working with DI is tracked here: https://github.com/Azure/azure-functions-dotnet-worker/issues/62

**Comment by onionhammer** [comment]
@sccrgoalie1 OK, so it works if it has the exact arguments it expects, it triggers. However, the service bus trigger is somewhat useless without access to the body. Are you able to get at it? byte[] arg fails and Message's 'Body' prroperty is null

**Comment by sccrgoalie1** [comment]
> @sccrgoalie1 OK, so it works if it has the exact arguments it expects, it triggers. However, the service bus trigger is somewhat useless without access to the body. Are you able to get at it? byte[] arg fails and Message's 'Body' prroperty is null

Right you are, it's null for me as well if I use a Message parameter.  I changed it to string and you can get the message body it appears.  I use the Label and UserProperties, but there doesn't seem to be a way to get those at the moment

**Comment by onionhammer** [comment]
@sccrgoalie1 have you tried deploying it or just run it locally? For me it works locally but when I deploy it the function never triggers.

**Comment by sccrgoalie1** [comment]
> @sccrgoalie1 have you tried deploying it or just run it locally? For me it works locally but when I deploy it the function never triggers.

Yeah, just got it deployed today.  It is firing when I publish using this command

`func azure functionapp publish <APP_NAME>`

**Comment by johnkors** [comment]
Getting a similar error:

```
[2021-02-16T14:58:09.309Z] Exception: Unable to convert to Microsoft.Azure.ServiceBus.Message
[2021-02-16T14:58:09.309Z] Stack:    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ConvertParameter(ParameterInfo param, TypedData value, ParameterConverterManager converterManager) in D:\a\1\s\src\DotNetWorker\Invocation\DefaultFunctionExecutor.cs:line 117
```

Full logs:

```
Trigger Details: MessageId: b2fc8142-2f08-4b56-8001-4cccf2196a2d, SequenceNumber: 48, DeliveryCount: 664, EnqueuedTimeUtc: 2021-02-16T14:57:35.9750000Z, LockedUntilUtc: 2021-02-16T15:03:09.2290000Z, SessionId: (null)
[2021-02-16T14:58:09.309Z] Executed 'Functions.JohnFunctionORAMA2' (Failed, Id=32919d7e-a8da-4cd1-a2de-c86637d6e9fb, Duration=1ms)
[2021-02-16T14:58:09.309Z] System.Private.CoreLib: Exception while executing function: Functions.JohnFunctionORAMA2. System.Private.CoreLib: Result: Failure
[2021-02-16T14:58:09.309Z] Exception: Unable to convert to Microsoft.Azure.ServiceBus.Message
[2021-02-16T14:58:09.309Z] Stack:    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ConvertParameter(ParameterInfo param, TypedData value, ParameterConverterManager converterManager) in D:\a\1\s\src\DotNetWorker\Invocation\DefaultFunctionExecutor.cs:line 117
[2021-02-16T14:58:09.309Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionExecutionContext context) in D:\a\1\s\src\DotNetWorker\Invocation\DefaultFunctionExecutor.cs:line 60
[2021-02-16T14:58:09.309Z]    at Microsoft.Azure.Functions.Worker.FunctionBroker.InvokeAsync(InvocationRequest invocationRequest) in D:\a\1\s\src\DotNetWorker\Broker\FunctionBroker.cs:line 44.
[2021-02-16T14:58:09.311Z] Message processing error (Action=UserCallback, ClientId=MessageReceiver1My.Functions, EntityPath=MyTest.Functions, Endpoint=myendpoint.servicebus.windows.net)
[2021-02-16T14:58:09.311Z] System.Private.CoreLib: Exception while executing function: Functions.JohnFunctionORAMA2. System.Private.CoreLib: Result: Failure
[2021-02-16T14:58:09.311Z] Exception: Unable to convert to Microsoft.Azure.ServiceBus.Message
[2021-02-16T14:58:09.311Z] Stack:    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ConvertParameter(ParameterInfo param, TypedData value, ParameterConverterManager converterManager) in D:\a\1\s\src\DotNetWorker\Invocation\DefaultFunctionExecutor.cs:line 117
[2021-02-16T14:58:09.311Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionExecutionContext context) in D:\a\1\s\src\DotNetWorker\Invocation\DefaultFunctionExecutor.cs:line 60
[2021-02-16T14:58:09.311Z]    at Microsoft.Azure.Functions.Worker.FunctionBroker.InvokeAsync(InvocationRequest invocationRequest) in D:\a\1\s\src\DotNetWorker\Broker\FunctionBroker.cs:line 44.

```

**Comment by sccrgoalie1** [comment]
> Getting a similar error:
> 
> ```
> [2021-02-16T14:58:09.309Z] Exception: Unable to convert to Microsoft.Azure.ServiceBus.Message
> [2021-02-16T14:58:09.309Z] Stack:    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ConvertParameter(ParameterInfo param, TypedData value, ParameterConverterManager converterManager) in D:\a\1\s\src\DotNetWorker\Invocation\DefaultFunctionExecutor.cs:line 117
> ```
> 
> Full logs:
> 
> ```
> Trigger Details: MessageId: b2fc8142-2f08-4b56-8001-4cccf2196a2d, SequenceNumber: 48, DeliveryCount: 664, EnqueuedTimeUtc: 2021-02-16T14:57:35.9750000Z, LockedUntilUtc: 2021-02-16T15:03:09.2290000Z, SessionId: (null)
> [2021-02-16T14:58:09.309Z] Executed 'Functions.JohnFunctionORAMA2' (Failed, Id=32919d7e-a8da-4cd1-a2de-c86637d6e9fb, Duration=1ms)
> [2021-02-16T14:58:09.309Z] System.Private.CoreLib: Exception while executing function: Functions.JohnFunctionORAMA2. System.Private.CoreLib: Result: Failure
> [2021-02-16T14:58:09.309Z] Exception: Unable to convert to Microsoft.Azure.ServiceBus.Message
> [2021-02-16T14:58:09.309Z] Stack:    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ConvertParameter(ParameterInfo param, TypedData value, ParameterConverterManager converterManager) in D:\a\1\s\src\DotNetWorker\Invocation\DefaultFunctionExecutor.cs:line 117
> [2021-02-16T14:58:09.309Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionExecutionContext context) in D:\a\1\s\src\DotNetWorker\Invocation\DefaultFunctionExecutor.cs:line 60
> [2021-02-16T14:58:09.309Z]    at Microsoft.Azure.Functions.Worker.FunctionBroker.InvokeAsync(InvocationRequest invocationRequest) in D:\a\1\s\src\DotNetWorker\Broker\FunctionBroker.cs:line 44.
> [2021-02-16T14:58:09.311Z] Message processing error (Action=UserCallback, ClientId=MessageReceiver1My.Functions, EntityPath=MyTest.Functions, Endpoint=myendpoint.servicebus.windows.net)
> [2021-02-16T14:58:09.311Z] System.Private.CoreLib: Exception while executing function: Functions.JohnFunctionORAMA2. System.Private.CoreLib: Result: Failure
> [2021-02-16T14:58:09.311Z] Exception: Unable to convert to Microsoft.Azure.ServiceBus.Message
> [2021-02-16T14:58:09.311Z] Stack:    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ConvertParameter(ParameterInfo param, TypedData value, ParameterConverterManager converterManager) in D:\a\1\s\src\DotNetWorker\Invocation\DefaultFunctionExecutor.cs:line 117
> [2021-02-16T14:58:09.311Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionExecutionContext context) in D:\a\1\s\src\DotNetWorker\Invocation\DefaultFunctionExecutor.cs:line 60
> [2021-02-16T14:58:09.311Z]    at Microsoft.Azure.Functions.Worker.FunctionBroker.InvokeAsync(InvocationRequest invocationRequest) in D:\a\1\s\src\DotNetWorker\Broker\FunctionBroker.cs:line 44.
> ```

What does you method look like. I got errors like that when I wasn't using string as the parameter type and when I had extra parameters.

**Comment by johnkors** [comment]
@sccrgoalie1 Updated my comment above with code details.

**Comment by sccrgoalie1** [comment]
> @sccrgoalie1 Updated my comment above with code details.

For me I had to change `Message myQueueItem` to `string myQueueItem`.  I was only able to figure out how to get at the body of the message.

**Comment by johnkors** [comment]
Hm, ok, right. Thanks. Using `string` as message gets me the body. Is there any other way to get `Message` or build `Message` from other parameters..?

**Comment by sccrgoalie1** [comment]
> Hm, ok, right. Thanks. Using `string` as message gets me the body. Is there any other way to get `Message` or build `Message` from other parameters..?

I tried for a while and couldn't get at them.  I was using label and user properties extensively.  I just converted over to sending that data in the body as a JSON object to get it going.
